---
- name: Request Tracker
  hosts: "{{ request_tracker_hosts }}"
  become: yes

  pre_tasks:
    - name: Check For Variables
      fail:
        msg: "Please pass the appropriate vars files with -e @/path/to/file.yml"
      when: request_tracker_vars_exist is undefined

  tasks:
    # - name: Install system_base
    #   include_role:
    #     name: system_base
    #   tags: [system_base]

    - name: Install request_tracker
      include_role:
        name: request_tracker
      tags: [request_tracker]